#
# Plugin and config created Brukill
# Discord: Brukill#1314 and @brukill
# My minecraft server NezerLand
# Discord server link: https://discord.gg/w8Uq55yCpX
#
#------------------------------------------------------------------------------------

# Экран
teleport-title: "&6Телепортация..."
teleport-subtitle: "&7Подождите..."

#------------------------------------------------------------------------------------

# Чат
teleport-message: "&aВы были телепортированы на координаты: &e%x%, %y%, %z%"

#------------------------------------------------------------------------------------

# Настройка RTP
teleport-delay: 3

#------------------------------------------------------------------------------------

# Конфигурация координат (желательно оставить y как он и стоит)

min-y: 60
max-y: 80

#------------------------------------------------------------------------------------

